#!/bin/bash
#
# Deploy kube federation control panel
#
# Prerequiesites: kubectl, kubefed, gcloud

source lib/kubefed

FED_NAME="federation"
declare -a CLUSTERS=("kubefed1" "kubefed2")
GCLOUD_DNS_NAME="kubefed"
GCLOUD_DNS_ZONE_NAME="kubefed.io"

# ONCE
gcloud::init_dns(){

  gcloud dns managed-zones create ${GCLOUD_DNS_NAME} --description="kubefed.io" --dns-name="${GCLOUD_DNS_ZONE_NAME}"

}

# This might take a few minutes
gcloud::init_clusters(){

  for c in ${CLUSTERS[@]}; do
  
    gcloud container clusters create $c \
      --zone "asia-east1-a" \
      --cluster-version="1.9.4-gke.1" \
      --disk-size="100" \
      --num-nodes="1" \
      --scopes "cloud-platform,storage-ro,logging-write,monitoring-write,service-control,service-management,https://www.googleapis.com/auth/ndev.clouddns.readwrite" \
      &
  
  done

  wait

}

#gcloud::init_clusters

kubefed::init

kubefed::join
