#!/bin/bash
#
# Deploy kube federation control panel
#
# Prerequiesites: kubectl, kubefed, gcloud

source lib/kubefed

FED_NAME="federation"
declare -a CLUSTERS=("kubefed1" "kubefed2")
GCLOUD_DNS_NAME="kubefed"
GCLOUD_DNS_ZONE_NAME="kubefed.io"

# ONCE
gcloud::init_dns(){

  gcloud dns managed-zones create ${GCLOUD_DNS_NAME} --description="kubefed.io" --dns-name="${GCLOUD_DNS_ZONE_NAME}"

}

kubefed::init

kubefed::join
