#!/bin/bash
#
# Unisntall kube federation

FED_NAME="federation"
FED_CLUSTER_NAME="kubefed1"
FED_CLSUTER_CONTEXT=$(kubectl config get-contexts | grep '*' | awk '{print $2}')
GCLOUD_DNS_NAME="kubefed"
GCLOUD_DNS_ZONE_NAME="kubefed.io"

kubectl delete namespace federation-system --context=${FED_CLUSTER_CONTEXT}
