#!/bin/bash
#
# Unisntall kube federation

source lib/kubefed

FED_NAME="federation"
declare -a CLUSTERS=("kubefed1" "kubefed2")
GCLOUD_DNS_NAME="kubefed"
GCLOUD_DNS_ZONE_NAME="kubefed.io"

kubefed::uninstall
