---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath-data
  annotations:
    volume.beta.kubernetes.io/storage-class: slow-one
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
